name: Next Rails Spec

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  next-spec:
    if: contains(github.head_ref, 'next-rails')
    runs-on: ubuntu-latest
    name: next-spec
    steps:
      - uses: actions/checkout@v4
      - name: Prepare spec
        run: |
          wget -nv http://sphinxsearch.com/files/dicts/en.pak
          docker compose run --rm -e BUNDLE_GEMFILE=Gemfile.next -e BUNDLE_CACHE_PATH=vendor/cache.next hackweek bundle exec rake dev:bootstrap --trace
      - name: Run tests
        run: docker compose run --rm -e BUNDLE_GEMFILE=Gemfile.next -e BUNDLE_CACHE_PATH=vendor/cache.next hackweek bundle exec rspec --color --format documentation
